begin;

-- Track whether an announcement was written by a person ('user') or generated by a cron job ('system').
-- System-generated announcements are displayed as authored by "Operations" rather than the super admin
-- whose ID we use for the FK on created_by.
alter table public.announcements
  add column if not exists source text not null default 'user';

alter table public.announcements
  drop constraint if exists announcements_source_check;

alter table public.announcements
  add constraint announcements_source_check
  check (source in ('user', 'system'));

create index if not exists idx_announcements_org_source_created
  on public.announcements(org_id, source, created_at desc);

-- Backfill existing rows that were created by the leave / holiday / birthday cron jobs.
update public.announcements
set source = 'system'
where source = 'user'
  and deleted_at is null
  and is_pinned = false
  and (
    title ilike '% is on annual leave'
    or title ilike '% is on sick leave'
    or title ilike '% is on personal days'
    or title ilike '% is on birthday leave'
    or title ilike '% is on maternity leave'
    or title ilike '% is on paternity leave'
    or title ilike '% is on leave'
    or title like 'Public Holiday (%)'
    or title like 'Happy birthday, %!'
  );

commit;
